# Generated by Django 2.2.6 on 2019-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_mix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sugerencia',
            field=models.TextField(null=True),
        ),
    ]
