# Generated by Django 2.2.7 on 2019-11-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_mix', '0003_ropa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
