# Generated by Django 2.2.7 on 2019-11-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_mix', '0004_ropa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='codigo',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='genero',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='marca',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='precio',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='tipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
