# Generated by Django 2.2.7 on 2019-11-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_mix', '0005_auto_20191115_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
